// Generated by purs bundle 0.14.9
var PS = {};
(function($PS) {
  "use strict";
  $PS["Api"] = $PS["Api"] || {};
  var exports = $PS["Api"];
  var square = function (n) {
      return n * n | 0;
  };
  exports["square"] = square;
})(PS);
module.exports = PS["Api"];
