// Generated by purs bundle 0.14.9
var PS = {};
(function(exports) {
  "use strict";

  exports.pow = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return Math.pow(x,y) | 0;
    };
  };
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function($PS) {
  // Generated by purs version 0.14.9
  "use strict";
  $PS["Data.Int"] = $PS["Data.Int"] || {};
  var exports = $PS["Data.Int"];
  var $foreign = $PS["Data.Int"];
  exports["pow"] = $foreign.pow;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.9
  "use strict";
  $PS["MlabsPlutusTemplate.Api"] = $PS["MlabsPlutusTemplate.Api"] || {};
  var exports = $PS["MlabsPlutusTemplate.Api"];
  var Data_Int = $PS["Data.Int"];                
  var square = function (n) {
      return Data_Int.pow(n)(2);
  };
  exports["square"] = square;
})(PS);
module.exports = PS["MlabsPlutusTemplate.Api"];
